<?php
/**
 * Compliance: Research-Use-Only disclaimers + Certificate of Analysis
 *
 * @package Shopping
 * Extracted from functions.php for maintainability.
 */
if ( ! defined( "ABSPATH" ) ) { exit; }

/* ═══════════════════════════════════════
   COMPLIANCE: Research-Use-Only disclaimers
   A prominent notice on every single-product page, plus a site-wide footer
   disclaimer on all front-end pages. All products are supplied strictly as
   research-grade material — not for human or animal consumption.
═══════════════════════════════════════ */

// Prominent notice directly under the product title/price on product pages.
/* ═══════════════════════════════════════
   CERTIFICATE OF ANALYSIS (COA)
   Per-product COA documents live in images/coa/<SKU>.pdf (printable) and
   images/coa/<SKU>.jpg (web preview), generated by generate_coa.py.
═══════════════════════════════════════ */
if ( ! function_exists( 'alluvia_coa_paths' ) ) {
    function alluvia_coa_paths( $sku ) {
        $sku  = sanitize_file_name( (string) $sku );
        if ( '' === $sku ) {
            return array( 'pdf' => '', 'img' => '' );
        }
        $dir  = trailingslashit( get_template_directory() ) . 'images/coa/';
        $uri  = trailingslashit( get_template_directory_uri() ) . 'images/coa/';
        return array(
            'pdf' => file_exists( $dir . $sku . '.pdf' ) ? $uri . $sku . '.pdf' : '',
            'img' => file_exists( $dir . $sku . '.jpg' ) ? $uri . $sku . '.jpg' : '',
        );
    }
    function alluvia_coa_url( $sku ) {
        $p = alluvia_coa_paths( $sku );
        return $p['pdf'];
    }
}

// COA results manifest (purity etc. per SKU), generated by generate_coa.py.
if ( ! function_exists( 'alluvia_coa_index' ) ) {
    function alluvia_coa_index() {
        static $idx = null;
        if ( null === $idx ) {
            $file = trailingslashit( get_template_directory() ) . 'images/coa/index.json';
            $idx  = file_exists( $file ) ? json_decode( file_get_contents( $file ), true ) : array();
            if ( ! is_array( $idx ) ) {
                $idx = array();
            }
        }
        return $idx;
    }
    function alluvia_coa_purity( $sku ) {
        $idx = alluvia_coa_index();
        return isset( $idx[ $sku ]['purity'] ) ? (float) $idx[ $sku ]['purity'] : null;
    }
}

// Download button on the single product page, matched by SKU.
add_action( 'woocommerce_single_product_summary', 'alluvia_product_coa_button', 26 );
function alluvia_product_coa_button() {
    global $product;
    if ( ! $product instanceof WC_Product ) {
        return;
    }
    $pdf = alluvia_coa_url( $product->get_sku() );
    if ( ! $pdf ) {
        return;
    }
    echo '<a href="' . esc_url( $pdf ) . '" target="_blank" rel="noopener" class="alluvia-coa-btn" '
        . 'style="display:inline-flex;align-items:center;gap:9px;margin:6px 0 4px;background:var(--white,#fff);color:var(--navy,#0a1a27);'
        . 'border:1.5px solid var(--gold,#c6a253);border-radius:100px;padding:11px 22px;font-family:inherit;font-weight:700;'
        . 'font-size:14px;text-decoration:none;transition:.25s;">'
        . '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--gold,#c6a253)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>'
        . 'Download Certificate of Analysis (PDF)</a>';
}

// Certificate of Analysis product tab (preview image + download), by SKU.
add_filter( 'woocommerce_product_tabs', 'alluvia_coa_product_tab' );
function alluvia_coa_product_tab( $tabs ) {
    global $product;
    if ( $product instanceof WC_Product ) {
        $paths = alluvia_coa_paths( $product->get_sku() );
        if ( $paths['pdf'] ) {
            $tabs['alluvia_coa'] = array(
                'title'    => __( 'Certificate of Analysis', 'shopping' ),
                'priority' => 25,
                'callback' => 'alluvia_coa_product_tab_content',
            );
        }
    }
    return $tabs;
}
function alluvia_coa_product_tab_content() {
    global $product;
    $paths = alluvia_coa_paths( $product instanceof WC_Product ? $product->get_sku() : '' );
    echo '<h2>Certificate of Analysis</h2>';
    $purity = $product instanceof WC_Product ? alluvia_coa_purity( $product->get_sku() ) : null;
    if ( null !== $purity ) {
        echo '<p style="font-size:18px;"><strong>RP-HPLC purity: ' . esc_html( number_format( $purity, 1 ) ) . '%</strong></p>';
    }
    echo '<p>Every batch is released against Alluvia Peptides specifications with identity (ESI-MS), '
        . 'RP-HPLC purity, water and acetate content verified. This material is supplied '
        . '<strong>for laboratory research use only</strong>.</p>';
    if ( $paths['img'] ) {
        echo '<a href="' . esc_url( $paths['pdf'] ) . '" target="_blank" rel="noopener">'
            . '<img src="' . esc_url( $paths['img'] ) . '" alt="Certificate of Analysis preview" '
            . 'loading="lazy" style="max-width:520px;width:100%;height:auto;border:1px solid #e3e8ec;border-radius:12px;box-shadow:0 8px 32px rgba(10,26,39,.14);" /></a>';
    }
    echo '<p style="margin-top:18px;"><a class="button alt" href="' . esc_url( $paths['pdf'] ) . '" '
        . 'target="_blank" rel="noopener">Download COA (PDF)</a></p>';
}

add_action( 'woocommerce_single_product_summary', 'alluvia_product_ruo_notice', 25 );
function alluvia_product_ruo_notice() {
    echo '<div class="alluvia-ruo-notice" role="note" style="margin:18px 0;padding:14px 16px;border:1px solid rgba(198,162,83,0.4);border-left:4px solid var(--gold,#c6a253);background:rgba(198,162,83,0.08);border-radius:8px;font-size:15px;line-height:1.5;color:rgba(255,255,255,0.85);">'
        . '<strong style="display:block;letter-spacing:1px;text-transform:uppercase;color:#c6a253;margin-bottom:4px;">For Research Use Only</strong>'
        . 'This product is supplied strictly for laboratory and in-vitro research by qualified researchers. '
        . 'It is <strong>not for human or animal consumption</strong> and is not a drug, food, cosmetic or dietary supplement.'
        . '</div>';
}

// Site-wide footer disclaimer on every front-end page.
add_action( 'wp_footer', 'alluvia_footer_disclaimer', 5 );
function alluvia_footer_disclaimer() {
    if ( is_admin() ) {
        return;
    }
    echo '<div class="alluvia-footer-disclaimer" style="background:var(--navy,#0a1a27);color:#aeb9c4;font-size:15px;line-height:1.6;text-align:center;padding:18px 20px;border-top:2px solid var(--gold,#c6a253);">'
        . '<div style="max-width:960px;margin:0 auto;">'
        . '<strong style="color:#fff;">Research Use Only &mdash; Not for Human Consumption.</strong> '
        . 'All products supplied by Alluvia Peptides are sold strictly as research-grade chemicals for in-vitro and laboratory research purposes only. '
        . 'They are not intended to diagnose, treat, cure or prevent any disease, and are not for human or veterinary use. '
        . 'By purchasing you confirm you are a qualified researcher or institution and accept full responsibility for safe, lawful handling.'
        . '</div></div>';
}

